name: CI Build

on:
  push:
    branches: [ main ]

  pull_request:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [1, 2, 3]
    steps:
      - name: Set output
        id: my_step
        run: echo "::set-output name=my_output::${{ matrix.config }}"
    outputs:
      matrix_output: ${{ steps.my_step.outputs.my_output }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Use Output
        run: echo "The output was ${{ needs.build.outputs.matrix_output }}"
