name: CI Build

on:
  push:
    branches: [ main ]

  pull_request:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Ruby ${{ matrix.ruby }} on ${{ matrix.operating-system }}

    env:
      NAME: Ruby ${{ matrix.ruby }} on ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', '3.2', head, jruby-head]
        operating-system: [ubuntu-latest]
        include:
          - ruby: '3.0'
            operating-system: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build successfully
        run: echo "SUCCESS"
        #run only if config is 1 or 3
        # if: ${{ matrix.ruby != 'head' }}

      # - name: Build failed
      #   run: echo "FAILED" && exit 1
      #   #run only if config is
      #   if: ${{ matrix.ruby == 'head' }}

      # - name: Get Current Job Log URL
      #   uses: Tiryoh/gha-jobid-action@v1
      #   id: jobs
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     job_name: "${{ github.job }}"


      # - name: Save status
      #   run: |
      #     mkdir -p status
      #     echo "${NAME}: ${{ job.status }}" > "status/$(date +'%Y%m%d%H%M%S') ${NAME}.txt"
      #   if: always()

      # - name: Upload status artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: status
      #     path: "status/*.txt"
      #   if: always()

  build-job2:
    needs: build
    runs-on: ubuntu-latest
    env:
      NAME: Build Job 2

    steps:
      - run: echo "SUCCESS"

      # - name: Save status
      #   run: |
      #     mkdir -p status
      #     echo "${NAME}: ${{ job.status }}" > "status/$(date +'%Y%m%d%H%M%S') ${NAME}.txt"
      #   if: always()

      # - name: Upload status artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: status
      #     path: "status/*.txt"
      #   if: always()

  report:
    needs: build-job2
    runs-on: ubuntu-latest
    steps:
      # - name: Download all artifacts
      #   uses: actions/download-artifact@v3

      - name: Output Job Info
        uses: .github/actions/job-info
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: all contexts
        run: |
          echo "{"
          echo "github: ${{ toJson(github) }},"
          echo "env: ${{ toJson(env) }},"
          echo "vars: ${{ toJson(vars) }},"
          echo "job: ${{ toJson(job) }},"
          echo "steps: ${{ toJson(steps) }},"
          echo "runner: ${{ toJson(runner) }},"
          echo "secrets: ${{ toJson(secrets) }},"
          echo "needs: ${{ toJson(needs) }},"
          echo "inputs: ${{ toJson(inputs) }}"
          echo "}"

      # - name: Get Current Job Log URL
      #   uses: Tiryoh/gha-jobid-action@v1
      #   id: jobs
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     job_name: "${{ github.job }}"

      # - name: Current Job ID and URL
      #   run: |
      #     echo ${{ steps.jobs.outputs.job_id }}
      #     echo ${{ steps.jobs.outputs.html_url }}

      # - name: Check statuses
      #   run: |
      #     ls status/*.txt | sort | while IFS= read -r file; do
      #       cat "$file"
      #     done

    if: always()
